### PR TITLE
add votekick feature

### PR DESCRIPTION
**Pull request by RiedleroD**
I can't always be online and neither can yuki. I say trusted users should be able to quickly kick nft scams, spammers, trolls, etc.

### CODE REVIEW

**Comment by RiedleroD** [comment]
should be working 100% now

**Comment by linegel** [comment]
Not merged? 🤔

**Comment by RiedleroD** [comment]
I think I wanted to add another thing. I forgot what it was though

**Comment by RiedleroD** [comment]
oh, it was #5 
well uh

that's a problem for future me

**Pull request merged**
