### PR TITLE
 kickvote alias added to main.py

### PR DESCRIPTION
**Pull request by CallofVoid**
added  a wrapper kind of aliasing to `/votekick` command, named `/kickvote`, this code is not tested so there is no proof that it works as expected.

### CODE REVIEW

**Comment by RiedleroD** [comment]
…what happened to the last few lines there?

also, you can just use the `@command` decorator twice on the same function

**Comment by CallofVoid** [comment]
Ah, I didn't know about that feature; if you mean the part with @command ... I just tried to make a wrapper-like hook to capture the alias command and then call the actual definition with stuff provided with the arguments in hook, and about the last line with red color in diff, I don't know; seems like change to line numbers are causing this behaviour

**Comment by RiedleroD** [comment]
well, *I* made the decorator as a wrapper, so … you couldn't have known, lol

**Comment by RiedleroD** [comment]
I'll try to fix the line thing tomorrow or so, don't worry about it

**Comment by purplesyringa** [comment]
I've implemented @RiedleroD's suggestion in #10.

**Pull request closed without merging**
